### ISSUE TITLE
Unable to load event list from TOA

### ISSUE THREAD

**Issue by jvens** [orange-alliance/TOA-DataSync#25]
When attempting to use the DS tool on Step 4 I am getting an HTTP 500 error to get the event list.  I can give you the entire call stack if you would like, but is line 25 of `setup.js`, and below is the full HTTP request that I see in the WebConsole.

`GET https://functions.theorangealliance.org/getAllCurrentWriteEvents` is returning `500`

Note I am using my myTOA account which is jeramie.vens(at)gmail(dot)com.

**Comment by ofekashery** [comment]
Hey @jvens, thanks for the reporting!
We had some server problems a few hours ago, did it happen to you at these moments?

**Comment by jvens** [comment]
Yes it happened just right before I submitted the issue.  I just restarted the app to see if the issue repeated and this time I get a different issue that is probably unrelated.  It appears that when I closed having not set an event it set the event to be `"undefined"`.  Below is the console output

```
internal/process/warning.js:18 (node:22936) ExperimentalWarning: The dns.promises API is experimental
loop.js:34 Uploading rankings... 
(8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
loop.js:34 UPLOADING match data and participants from undefined-Q001-1
loop.js:34 UPLOADING match data and participants from undefined-Q003-1
loop.js:34 UPLOADING match data and participants from undefined-Q002-1
loop.js:34 UPLOADING match data and participants from undefined-Q006-1
loop.js:34 UPLOADING match data and participants from undefined-Q005-1
loop.js:34 UPLOADING match data and participants from undefined-Q004-1
loop.js:34 UPLOADING match data and participants from undefined-Q007-1
loop.js:34 UPLOADING match data and participants from undefined-Q008-1
loop.js:34 UPLOADING match data and participants from undefined-Q009-1
loop.js:34 UPLOADING match data and participants from undefined-Q010-1
loop.js:34 UPLOADING match data and participants from undefined-Q012-1
loop.js:34 UPLOADING match data and participants from undefined-Q011-1
loop.js:34 UPLOADING match data and participants from undefined-Q013-1
C:\Users\jeram\Docum…adapters\xhr.js:160 GET https://theorangealliance.org/api/event/undefined 400 (Bad Request)
C:\Users\jeram\Docum…ts\js\sync-ui.js:42 
{data: {…}, status: 400, statusText: "Bad Request", headers: {…}, config: {…}, …}
C:\Users\jeram\Docum…adapters\xhr.js:160 DELETE https://theorangealliance.org/api/event/undefined/teams 400 (Bad Request)
loop.js:34 Bad Request DELETE /event/undefined/teams 
{}
C:\Users\jeram\Docum…adapters\xhr.js:160 DELETE https://theorangealliance.org/api/event/undefined/rankings 400 (Bad Request)
loop.js:34 Bad Request DELETE /event/undefined/rankings 
{}
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
2
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
2
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/participants 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/participants 
(4) [{…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/teams 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/teams 
(10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/rankings 400 (Bad Request)
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/details 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches/details 
[{…}]
loop.js:34 Bad Request POST /event/undefined/rankings 
(8) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches 400 (Bad Request)
loop.js:34 Bad Request POST /event/undefined/matches 
[{…}]
loop.js:34 Event Status: 2
C:\Users\jeram\Docum…adapters\xhr.js:160 POST https://theorangealliance.org/api/event/undefined/matches/details 400 (Bad Request)
```

I cleared local storage and restarted the app to start over the process from Step 1 and was able to repeat the 500 issue.

~~~
C:\Users\jeram\Docum…adapters\xhr.js:160 GET https://functions.theorangealliance.org/getAllCurrentWriteEvents 500
setup.js:29 Error: Request failed with status code 500
    at createError (C:\Users\jeram\Docum…e\createError.js:16)
    at settle (C:\Users\jeram\Docum…b\core\settle.js:18)
    at XMLHttpRequest.handleLoad (C:\Users\jeram\Docum…\adapters\xhr.js:59)
setup.js:31 Error in getting cloud
~~~

**Comment by ofekashery** [comment]
I fixed now the ``getAllCurrentWriteEvents``, thanks!!
The undefined event is interesting, I'll check it out.

**Comment by jvens** [comment]
I am sorry for muddying up this thread with multiple issues, but I think it might be the easiest way to do it.

So now I can see the event list, but if I select an event I now get a `500` error for `https://functions.theorangealliance.org/getAPIKey`.

I thought maybe I need to generate the key on myTOA first, so I logged into that and click `GENERATE A KEY` on the website.  I then get a CORS error:

```
events:1 Access to XMLHttpRequest at 'https://functions.theorangealliance.org/eventKey' from origin 'https://theorangealliance.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.0f3882f….js:1 
e {headers: t, status: 0, statusText: "Unknown Error", url: "https://functions.theorangealliance.org/eventKey", ok: false, …}
VM175:1 GET https://functions.theorangealliance.org/eventKey net::ERR_FAILED
```

I don't know if they are related or not since I can't see the server side logs for this issue.

**Comment by jvens** [comment]
I want to add a little more info to this issue.  Here is the HTTP Headers for the request that is failing:
![image](https://user-images.githubusercontent.com/7074504/66064443-0141c800-e50b-11e9-8a3d-a99c5831ffa2.png)

I already verified that the Authorization token is valid.  The actual body of the response is `Error: could not handle the request`.  Nothing stands out here as a reason the request would have failed unless there is some bug on the server side.  Let me know if you need any further information.

Note, I have seen this exact issue now on two different computers, and on Windows & Linux.

**Comment by Techno11** [comment]
Thanks for giving us so many details, allowing us to debug these issues.  We apologise for any inconveniences that are caused by this new software, but we appreciate you working with us to resolve them.  The Cloud Functions requests seem to be the culprit here, so we'll be taking a look today.  It's possible these issues may be caused due to the fact that we reloaded the events table yesterday.  Thanks again.

**Comment by jvens** [comment]
@Techno11, not a problem.  We still have a couple of weeks before the first events and I would rather work through the bugs now.

**Comment by ofekashery** [comment]
@jvens It should work now, would you like to try?

**Comment by jvens** [comment]
@ofekashery, It is now working.  Thank you for the quick resolution.  I will run it through more exhaustive tests over the next couple of days and let you know if I run into any more bugs.
